namespace TypeFaster.ConsoleApp.Display
{
    /// <summary>
    /// This class is responsible for writing content to the Console.
    /// </summary>
    public static class UserInterface
    {
        #region Public Methods

        /// <summary>
        /// Write the provided content to the console.
        /// </summary>
        /// <param name="displayedContent"></param>
        public static void Display(DisplayedContent displayedContent)
        {
            foreach (var text in displayedContent.DisplayedText)
            {
                WriteDisplayedText(text);
            }
        }

        /// <summary>
        /// Writes the content generated by the IDisplayComponent to the console.
        /// </summary>
        /// <param name="component">The IDisplayComponent that will provide the DisplayedContent to write to the console.</param>
        public static void Display(IDisplayComponent component) =>
            Display(component.GetDisplayedContent());

        #endregion

        #region Private Helper Methods

        /// <summary>
        /// Private helper method for writing DisplayedText to the console.
        /// </summary>
        /// <param name="displayed">The DisplayedText to write to the console.</param>
        private static void WriteDisplayedText(DisplayedText displayed)
        {
            Console.SetCursorPosition(displayed.PositionX, displayed.PositionY);

            Console.ForegroundColor = displayed.FontColor;

            Console.BackgroundColor = displayed.BackgroundColor;

            Console.Write(displayed.Value);
        }

        #endregion
    }
}
